
source 'http://cooder.linkdoc.com:9999/iOS/linkdoc_pods.git'

install! 'cocoapods',
  disable_input_output_paths: true,
  generate_multiple_pod_projects: true


platform :ios, '10.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
